package com.swent.skillswap.post

enum class PostTags {
    ARCHITECTURE,
    CHEMISTRY,
    CIVIL_ENGINEERING,
    COMPUTER_SCIENCE,
    ELECTRICAL_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING,
    LIFE_SCIENCES,
    MATERIALS_SCIENCE,
    MATHEMATICS,
    MECHANICAL_ENGINEERING,
    MICROENGINEERING,
    PHYSICS,
    COMMUNICATION_SYSTEMS,
    DATA_SCIENCE,
    FINANCIAL_ENGINEERING,
    MANAGEMENT_OF_TECHNOLOGY,
    NEUROSCIENCES,
    ROBOTICS,
}