package com.swent.skillswap.utils

import android.content.Context
import androidx.core.os.bundleOf
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.Companion.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject

/**
 * A test utility class that mocks Android's [CredentialManager] for authentication tests.
 *
 * This fake manager allows you to simulate a Google Sign-In flow without needing a real Google
 * account or network interaction.
 *
 * The mock is configured to always return a [CustomCredential] containing a fake Google ID token
 * provided by the caller.
 *
 * Usage:
 * ```
 * val fakeToken = FakeJwtGenerator.createFakeGoogleIdToken("John Doe", "john@example.com")
 * val credentialManager = FakeCredentialManager.create(fakeToken)
 * ```
 *
 * This setup ensures that any call to [CredentialManager.getCredential] during tests will return a
 * [GetCredentialResponse] with the provided fake token, allowing you to test authentication logic
 * in isolation.
 *
 * ⚠️ **Important:** This should only be used in test environments. Never include this class or its
 * usage in production builds.
 */
class FakeCredentialManager private constructor(private val context: Context) :
    CredentialManager by CredentialManager.create(context) {

    companion object {
        /**
         * Creates a mocked [CredentialManager] that always returns a fake [CustomCredential] with
         * the specified fake ID token when [CredentialManager.getCredential] is invoked.
         *
         * @param fakeUserIdToken A fake JWT string, typically generated by [FakeJwtGenerator].
         * @return A [CredentialManager] mock preconfigured for testing.
         */
        fun create(fakeUserIdToken: String): CredentialManager {
            mockkObject(GoogleIdTokenCredential)
            val googleIdTokenCredential = mockk<GoogleIdTokenCredential>()
            every { googleIdTokenCredential.idToken } returns fakeUserIdToken
            every { GoogleIdTokenCredential.createFrom(any()) } returns googleIdTokenCredential
            val fakeCredentialManager = mockk<FakeCredentialManager>()
            val mockGetCredentialResponse = mockk<GetCredentialResponse>()

            val fakeCustomCredential =
                CustomCredential(
                    type = TYPE_GOOGLE_ID_TOKEN_CREDENTIAL,
                    data = bundleOf("id_token" to fakeUserIdToken)
                )

            every { mockGetCredentialResponse.credential } returns fakeCustomCredential
            coEvery {
                fakeCredentialManager.getCredential(any<Context>(), any<GetCredentialRequest>())
            } returns mockGetCredentialResponse

            return fakeCredentialManager
        }
    }
}
